export const VifEventsABI = [
	{
		type: 'event',
		name: 'MarketOrder',
		inputs: [
			{
				name: 'market',
				type: 'bytes32',
				indexed: true,
				internalType: 'bytes32',
			},
			{
				name: 'taker',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{ name: 'got', type: 'uint256', indexed: false, internalType: 'uint256' },
			{
				name: 'gave',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{ name: 'fee', type: 'uint256', indexed: false, internalType: 'uint256' },
			{
				name: 'bounty',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'fillVolume',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{ name: 'fillWants', type: 'bool', indexed: false, internalType: 'bool' },
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'NewOffer',
		inputs: [
			{
				name: 'market',
				type: 'bytes32',
				indexed: true,
				internalType: 'bytes32',
			},
			{
				name: 'offerId',
				type: 'uint40',
				indexed: true,
				internalType: 'uint40',
			},
			{
				name: 'maker',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'gives',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{ name: 'tick', type: 'int24', indexed: false, internalType: 'int24' },
			{
				name: 'expiry',
				type: 'uint32',
				indexed: false,
				internalType: 'uint32',
			},
			{
				name: 'provision',
				type: 'uint24',
				indexed: false,
				internalType: 'uint24',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'OfferCancelled',
		inputs: [
			{
				name: 'market',
				type: 'bytes32',
				indexed: true,
				internalType: 'bytes32',
			},
			{
				name: 'offerId',
				type: 'uint40',
				indexed: true,
				internalType: 'uint40',
			},
			{
				name: 'outbound',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'inbound',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'provision',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'OfferClaimed',
		inputs: [
			{
				name: 'market',
				type: 'bytes32',
				indexed: true,
				internalType: 'bytes32',
			},
			{
				name: 'offerId',
				type: 'uint40',
				indexed: true,
				internalType: 'uint40',
			},
			{
				name: 'outbound',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'inbound',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'provision',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'OfferUpdated',
		inputs: [
			{
				name: 'market',
				type: 'bytes32',
				indexed: true,
				internalType: 'bytes32',
			},
			{
				name: 'offerId',
				type: 'uint40',
				indexed: true,
				internalType: 'uint40',
			},
			{
				name: 'gives',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'claimedReceived',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{ name: 'tick', type: 'int24', indexed: false, internalType: 'int24' },
			{
				name: 'expiry',
				type: 'uint32',
				indexed: false,
				internalType: 'uint32',
			},
			{
				name: 'provision',
				type: 'uint24',
				indexed: false,
				internalType: 'uint24',
			},
		],
		anonymous: false,
	},
] as const
