export const VifAbi = [
	{
		type: 'constructor',
		inputs: [
			{ name: 'owner', type: 'address', internalType: 'address' },
			{ name: 'provision', type: 'uint24', internalType: 'uint24' },
		],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'authorize',
		inputs: [
			{ name: 'authorized', type: 'address', internalType: 'address' },
			{ name: 'value', type: 'bool', internalType: 'bool' },
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'authorizeWithSig',
		inputs: [
			{
				name: 'authorization',
				type: 'tuple',
				internalType: 'struct Authorization',
				components: [
					{ name: 'authorizer', type: 'address', internalType: 'address' },
					{ name: 'authorized', type: 'address', internalType: 'address' },
					{ name: 'isAuthorized', type: 'bool', internalType: 'bool' },
					{ name: 'nonce', type: 'uint256', internalType: 'uint256' },
					{ name: 'deadline', type: 'uint256', internalType: 'uint256' },
				],
			},
			{ name: 'signature', type: 'bytes', internalType: 'bytes' },
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'cancel',
		inputs: [
			{ name: 'marketId', type: 'bytes32', internalType: 'bytes32' },
			{ name: 'offerId', type: 'uint40', internalType: 'uint40' },
		],
		outputs: [
			{ name: 'inbound', type: 'uint256', internalType: 'uint256' },
			{ name: 'outbound', type: 'uint256', internalType: 'uint256' },
			{ name: 'provision', type: 'uint256', internalType: 'uint256' },
		],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'cancelOwnershipHandover',
		inputs: [],
		outputs: [],
		stateMutability: 'payable',
	},
	{
		type: 'function',
		name: 'claim',
		inputs: [
			{ name: 'marketId', type: 'bytes32', internalType: 'bytes32' },
			{ name: 'offerId', type: 'uint40', internalType: 'uint40' },
		],
		outputs: [
			{ name: 'inbound', type: 'uint256', internalType: 'uint256' },
			{ name: 'outbound', type: 'uint256', internalType: 'uint256' },
			{ name: 'provision', type: 'uint256', internalType: 'uint256' },
		],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'clean',
		inputs: [
			{ name: 'marketId', type: 'bytes32', internalType: 'bytes32' },
			{ name: 'offerId', type: 'uint40', internalType: 'uint40' },
		],
		outputs: [
			{ name: 'bounty', type: 'uint256', internalType: 'uint256' },
			{ name: 'success', type: 'bool', internalType: 'bool' },
		],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'clear',
		inputs: [
			{ name: 'token', type: 'address', internalType: 'address' },
			{ name: 'amount', type: 'uint256', internalType: 'uint256' },
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'completeOwnershipHandover',
		inputs: [
			{ name: 'pendingOwner', type: 'address', internalType: 'address' },
		],
		outputs: [],
		stateMutability: 'payable',
	},
	{
		type: 'function',
		name: 'consume',
		inputs: [
			{ name: 'taker', type: 'address', internalType: 'address' },
			{ name: 'marketId', type: 'bytes32', internalType: 'bytes32' },
			{ name: 'maxTick', type: 'int24', internalType: 'int24' },
			{ name: 'fillVolume', type: 'uint256', internalType: 'uint256' },
			{ name: 'fillWants', type: 'bool', internalType: 'bool' },
			{ name: 'maxOffers', type: 'uint256', internalType: 'uint256' },
		],
		outputs: [
			{ name: 'gave', type: 'uint256', internalType: 'uint256' },
			{ name: 'got', type: 'uint256', internalType: 'uint256' },
			{ name: 'fee', type: 'uint256', internalType: 'uint256' },
			{ name: 'bounty', type: 'uint256', internalType: 'uint256' },
		],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'eip712Domain',
		inputs: [],
		outputs: [
			{ name: 'fields', type: 'bytes1', internalType: 'bytes1' },
			{ name: 'name', type: 'string', internalType: 'string' },
			{ name: 'version', type: 'string', internalType: 'string' },
			{ name: 'chainId', type: 'uint256', internalType: 'uint256' },
			{ name: 'verifyingContract', type: 'address', internalType: 'address' },
			{ name: 'salt', type: 'bytes32', internalType: 'bytes32' },
			{ name: 'extensions', type: 'uint256[]', internalType: 'uint256[]' },
		],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'extsload',
		inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
		outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'exttload',
		inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
		outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'initialize',
		inputs: [
			{ name: 'owner', type: 'address', internalType: 'address' },
			{ name: 'provision', type: 'uint24', internalType: 'uint24' },
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'lock',
		inputs: [{ name: 'data', type: 'bytes', internalType: 'bytes' }],
		outputs: [{ name: 'result', type: 'bytes', internalType: 'bytes' }],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'make',
		inputs: [
			{ name: 'maker', type: 'address', internalType: 'address' },
			{ name: 'marketId', type: 'bytes32', internalType: 'bytes32' },
			{ name: 'initialOfferId', type: 'uint40', internalType: 'uint40' },
			{ name: 'gives', type: 'uint256', internalType: 'uint256' },
			{ name: 'tick', type: 'int24', internalType: 'int24' },
			{ name: 'expiry', type: 'uint32', internalType: 'uint32' },
			{ name: 'provision', type: 'uint24', internalType: 'uint24' },
		],
		outputs: [
			{ name: 'offerId', type: 'uint40', internalType: 'uint40' },
			{ name: 'claimedReceived', type: 'uint256', internalType: 'uint256' },
		],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'openMarket',
		inputs: [
			{ name: 'outboundToken', type: 'address', internalType: 'address' },
			{ name: 'inboundToken', type: 'address', internalType: 'address' },
			{ name: 'outboundUnits', type: 'uint64', internalType: 'uint64' },
			{ name: 'inboundUnits', type: 'uint64', internalType: 'uint64' },
			{ name: 'tickSpacing', type: 'uint16', internalType: 'uint16' },
			{ name: 'fees', type: 'uint16', internalType: 'uint16' },
			{ name: 'minOutboundUnits', type: 'uint32', internalType: 'uint32' },
		],
		outputs: [{ name: 'marketId', type: 'bytes32', internalType: 'bytes32' }],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'owner',
		inputs: [],
		outputs: [{ name: 'result', type: 'address', internalType: 'address' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'ownershipHandoverExpiresAt',
		inputs: [
			{ name: 'pendingOwner', type: 'address', internalType: 'address' },
		],
		outputs: [{ name: 'result', type: 'uint256', internalType: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'renounceOwnership',
		inputs: [],
		outputs: [],
		stateMutability: 'payable',
	},
	{
		type: 'function',
		name: 'requestOwnershipHandover',
		inputs: [],
		outputs: [],
		stateMutability: 'payable',
	},
	{
		type: 'function',
		name: 'setActive',
		inputs: [
			{ name: 'marketId', type: 'bytes32', internalType: 'bytes32' },
			{ name: 'active', type: 'bool', internalType: 'bool' },
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'setBlacklisted',
		inputs: [
			{ name: 'user', type: 'address', internalType: 'address' },
			{ name: 'blacklisted', type: 'bool', internalType: 'bool' },
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'setFees',
		inputs: [
			{ name: 'marketId', type: 'bytes32', internalType: 'bytes32' },
			{ name: 'fees', type: 'uint16', internalType: 'uint16' },
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'setMinOutboundUnits',
		inputs: [
			{ name: 'marketId', type: 'bytes32', internalType: 'bytes32' },
			{ name: 'minOutboundUnits', type: 'uint32', internalType: 'uint32' },
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'setPaused',
		inputs: [{ name: 'paused', type: 'bool', internalType: 'bool' }],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'setProvisions',
		inputs: [{ name: 'provision', type: 'uint24', internalType: 'uint24' }],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'settle',
		inputs: [
			{ name: 'token', type: 'address', internalType: 'address' },
			{ name: 'amount', type: 'uint256', internalType: 'uint256' },
			{ name: 'from', type: 'address', internalType: 'address' },
		],
		outputs: [],
		stateMutability: 'payable',
	},
	{
		type: 'function',
		name: 'take',
		inputs: [
			{ name: 'token', type: 'address', internalType: 'address' },
			{ name: 'amount', type: 'uint256', internalType: 'uint256' },
			{ name: 'receiver', type: 'address', internalType: 'address' },
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'transferOwnership',
		inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
		outputs: [],
		stateMutability: 'payable',
	},
	{
		type: 'function',
		name: 'withdrawFees',
		inputs: [
			{ name: 'token', type: 'address', internalType: 'address' },
			{ name: 'amount', type: 'uint256', internalType: 'uint256' },
			{ name: 'receiver', type: 'address', internalType: 'address' },
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'event',
		name: 'MarketOrder',
		inputs: [
			{
				name: 'market',
				type: 'bytes32',
				indexed: true,
				internalType: 'bytes32',
			},
			{
				name: 'taker',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{ name: 'got', type: 'uint256', indexed: false, internalType: 'uint256' },
			{
				name: 'gave',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{ name: 'fee', type: 'uint256', indexed: false, internalType: 'uint256' },
			{
				name: 'bounty',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'fillVolume',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{ name: 'fillWants', type: 'bool', indexed: false, internalType: 'bool' },
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'NewOffer',
		inputs: [
			{
				name: 'market',
				type: 'bytes32',
				indexed: true,
				internalType: 'bytes32',
			},
			{
				name: 'offerId',
				type: 'uint40',
				indexed: true,
				internalType: 'uint40',
			},
			{
				name: 'maker',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'gives',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{ name: 'tick', type: 'int24', indexed: false, internalType: 'int24' },
			{
				name: 'expiry',
				type: 'uint32',
				indexed: false,
				internalType: 'uint32',
			},
			{
				name: 'provision',
				type: 'uint24',
				indexed: false,
				internalType: 'uint24',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'OfferCancelled',
		inputs: [
			{
				name: 'market',
				type: 'bytes32',
				indexed: true,
				internalType: 'bytes32',
			},
			{
				name: 'offerId',
				type: 'uint40',
				indexed: true,
				internalType: 'uint40',
			},
			{
				name: 'outbound',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'inbound',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'provision',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'OfferClaimed',
		inputs: [
			{
				name: 'market',
				type: 'bytes32',
				indexed: true,
				internalType: 'bytes32',
			},
			{
				name: 'offerId',
				type: 'uint40',
				indexed: true,
				internalType: 'uint40',
			},
			{
				name: 'outbound',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'inbound',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'provision',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'OfferCleaned',
		inputs: [
			{
				name: 'market',
				type: 'bytes32',
				indexed: true,
				internalType: 'bytes32',
			},
			{
				name: 'offerId',
				type: 'uint40',
				indexed: true,
				internalType: 'uint40',
			},
			{
				name: 'bounty',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'OfferUpdated',
		inputs: [
			{
				name: 'market',
				type: 'bytes32',
				indexed: true,
				internalType: 'bytes32',
			},
			{
				name: 'offerId',
				type: 'uint40',
				indexed: true,
				internalType: 'uint40',
			},
			{
				name: 'gives',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{
				name: 'claimedReceived',
				type: 'uint256',
				indexed: false,
				internalType: 'uint256',
			},
			{ name: 'tick', type: 'int24', indexed: false, internalType: 'int24' },
			{
				name: 'expiry',
				type: 'uint32',
				indexed: false,
				internalType: 'uint32',
			},
			{
				name: 'provision',
				type: 'uint24',
				indexed: false,
				internalType: 'uint24',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'OwnershipHandoverCanceled',
		inputs: [
			{
				name: 'pendingOwner',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'OwnershipHandoverRequested',
		inputs: [
			{
				name: 'pendingOwner',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'OwnershipTransferred',
		inputs: [
			{
				name: 'oldOwner',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
			{
				name: 'newOwner',
				type: 'address',
				indexed: true,
				internalType: 'address',
			},
		],
		anonymous: false,
	},
	{ type: 'error', name: 'AlreadyInitialized', inputs: [] },
	{ type: 'error', name: 'AmountOverflow', inputs: [] },
	{ type: 'error', name: 'AuthorizationExpired', inputs: [] },
	{ type: 'error', name: 'DensityTooLow', inputs: [] },
	{ type: 'error', name: 'InvalidExpiry', inputs: [] },
	{ type: 'error', name: 'InvalidMinOutboundUnits', inputs: [] },
	{ type: 'error', name: 'InvalidTickSpacing', inputs: [] },
	{ type: 'error', name: 'InvalidUnits', inputs: [] },
	{ type: 'error', name: 'NewOwnerIsZeroAddress', inputs: [] },
	{ type: 'error', name: 'NoHandoverRequest', inputs: [] },
	{ type: 'error', name: 'NonExistentOffer', inputs: [] },
	{ type: 'error', name: 'NotActive', inputs: [] },
	{ type: 'error', name: 'NotAuthorized', inputs: [] },
	{ type: 'error', name: 'UnableToSettleNative', inputs: [] },
	{ type: 'error', name: 'Unauthorized', inputs: [] },
] as const
